apiVersion: v1
kind: Service
metadata:
  labels:    
     app: simple-db-api-java
  name: simple-db-api-java
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: simple-db-api-java
  type: ClusterIP