spring:
    datasource:
        url:
        username:
        password:
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8080

