apiVersion: v1
kind: Service
metadata:
  labels:    
     app: simple-db-api-frontend
  name: simple-db-api-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 8081
  selector:
    app: simple-db-api-frontend
  type: ClusterIP