kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-java
  labels:
    type: local
    app: postgres-java
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-java"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-java
  labels:
    app: postgres-java
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Mi