apiVersion: apps/v1
kind: StatefulSet
metadata:
   labels:
      app: postgres
   name: postgres
   namespace: {{ .Release.Namespace }}
spec:
   serviceName: "postgres"
   replicas: 1
   selector:
      matchLabels:
         app: postgres
   template:
      metadata:
         labels:
            app: postgres
         annotations:
            sidecar.istio.io/inject: "true"
            traffic.sidecar.istio.io/includeInboundPorts: "5432"
      spec:
         containers:
            - name: postgres
              image: tehcyx/postgres:0.2.0
              env:
               - name: POSTGRES_DB
                 valueFrom:
                  configMapKeyRef:
                     name: postgres-config
                     key: POSTGRES_DB
               - name: POSTGRES_USER
                 valueFrom:
                  configMapKeyRef:
                     name: postgres-config
                     key: POSTGRES_USER
               - name: POSTGRES_PASSWORD
                 valueFrom:
                  secretKeyRef:
                     name: postgres-secret
                     key: POSTGRES_PASSWORD
              ports:
              - containerPort: 5432
                name: postgresdb
              volumeMounts:
              - name: postgresdb
                mountPath: /var/lib/postgresql/data
         volumes:
            - name: postgresdb
              persistentVolumeClaim:
                claimName: postgres-pv-claim